catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

set xocc_optimize_level 0
open_project gcnconv_kernel
set_top gcnconv_kernel
add_files "/home/centos/CS_259/Project/GCN_FPGA/src/merlin/.merlin_prj/run/implement/exec/hls/__merlinkernel_gcnconv_kernel.cpp" -cflags " -D XILINX -I /home/centos/CS_259/Project/GCN_FPGA/src/merlin -I /home/centos/CS_259/Project/GCN_FPGA/src/merlin -I /opt/merlin/mars-gen/lib/merlin -I /home/centos/CS_259/Project/GCN_FPGA/src/merlin/.merlin_prj/run/implement/exec/hls "
open_solution solution
set_part xcvu9p-flgb2104-2-i
create_clock -period 250MHz -name default
config_sdx -target xocc
config_rtl -kernel_profile
config_export -vivado_optimization_level $xocc_optimize_level
config_dataflow -strict_mode warning
config_debug -enable
set_clock_uncertainty 27.000000%
config_interface -m_axi_addr64
config_export -format ip_catalog -ipname gcnconv_kernel
source "/home/centos/CS_259/Project/GCN_FPGA/src/merlin/.merlin_prj/run/implement/exec/hls/my_hls_pre.tcl"
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
